# Numpy

Almacenar un array de numpy en una variable

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

Mostrar un vector a partir desde una posición especifica

In [3]:
a[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

Mostrar un vector desde una posición a otra

In [4]:
a[2:5]

array([3, 4, 5])

Mostrar los valores de un posición saltando X elementos por intervalos

In [5]:
a[1::4]

array([ 2,  6, 10])

Crear un vector de ceros

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

Crear un Array de unos

In [8]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Crear datos espaceados

In [10]:
#Params: (valor minimo, valor máximo, cantidad de elementos)
np.linspace(3, 10, 5)

array([ 3.  ,  4.75,  6.5 ,  8.25, 10.  ])

Crear una matriz

In [15]:
b = np.array([['x','y','z'],['a','b','c']])
b

array([['x', 'y', 'z'],
       ['a', 'b', 'c']], dtype='<U1')

Conocer el número de dimensiones

In [16]:
b.ndim

2

Ordenar los valores en un vector de menor a mayor

In [17]:
c = [12, 4, 10, 40, 2]
np.sort(c)

array([ 2,  4, 10, 12, 40])

Trabajar con datos complejos

In [22]:
cabeceras = [ ('nombre','S10'), ('edad',int)]
datos = [('Juan',10), ('Maria',70), ('Javier',42), ('Samuel', 15)]
usuarios = np.array(datos, dtype = cabeceras)

np.sort(usuarios, order = 'edad')

array([(b'Juan', 10), (b'Samuel', 15), (b'Javier', 42), (b'Maria', 70)],
      dtype=[('nombre', 'S10'), ('edad', '<i4')])

Rellenar vectores de forma dinámica

In [23]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
np.arange(5,30)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [25]:
np.arange(5,50,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

Rellenar una matriz

In [26]:
np.full((3,5), 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

Crear una matriz diagonal

In [27]:
np.diag([0,1,2,3,5,8])

array([[0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 8]])

## Reto
Crear un array de tres dimensiones y ordenar a partir del nombre, edad y país

In [28]:
cabeceras = [ ('nombre','S10'), ('edad',int),('pais','S10')]
datos = [('Juan',10,'Colombia'), ('Maria',70,'Brasil'), ('Javier',42, 'Peru'), ('Samuel', 15, 'Francia')]
usuarios = np.array(datos, dtype = cabeceras)

In [29]:
np.sort(usuarios, order = 'nombre')

array([(b'Javier', 42, b'Peru'), (b'Juan', 10, b'Colombia'),
       (b'Maria', 70, b'Brasil'), (b'Samuel', 15, b'Francia')],
      dtype=[('nombre', 'S10'), ('edad', '<i4'), ('pais', 'S10')])

In [30]:
np.sort(usuarios, order = 'edad')

array([(b'Juan', 10, b'Colombia'), (b'Samuel', 15, b'Francia'),
       (b'Javier', 42, b'Peru'), (b'Maria', 70, b'Brasil')],
      dtype=[('nombre', 'S10'), ('edad', '<i4'), ('pais', 'S10')])

In [31]:
np.sort(usuarios, order = 'pais')

array([(b'Maria', 70, b'Brasil'), (b'Juan', 10, b'Colombia'),
       (b'Samuel', 15, b'Francia'), (b'Javier', 42, b'Peru')],
      dtype=[('nombre', 'S10'), ('edad', '<i4'), ('pais', 'S10')])